# Generated by Django 5.2.4 on 2025-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todo",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
