# Generated by Django 5.2.4 on 2025-07-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_todo_completed_todo_created_todo_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="end_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
