# Generated by Django 5.2.4 on 2025-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_todo_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="end_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
