# Generated by Django 5.2.4 on 2025-07-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todo_end_date_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
